name: publish
on:
  push:
    branches:
      - main
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'

      - name: NPM Install
        run: npm ci

      - name: Build
        run: npm run build

      - name: Publish
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_USERNAME: ${{ secrets.NPM_USERNAME }}
          NPM_PASSWORD: ${{ secrets.NPM_PASSWORD }}
          NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
